version: '{build}'
branches:
  only:
  - master
  - appveyor
  - /^maint.*/
environment:
  GITTEST_INVASIVE_FS_STRUCTURE: 1
  GITTEST_INVASIVE_FS_SIZE: 1

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    CMAKE_OPTIONS: -G"Visual Studio 10 2010"
    ARCH: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    CMAKE_OPTIONS: -G"Visual Studio 10 2010 Win64"
    ARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"Visual Studio 14 2015"
    ARCH: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"Visual Studio 14 2015 Win64"
    ARCH: amd64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: amd64

install:
- set PATH=%TEMP%\mingw64\bin;%TEMP%\mingw32\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CMake\bin
- ps: |
    mkdir build
    cd build
    if ($env:CMAKE_OPTIONS -eq '-G"MinGW Makefiles"') {
      ../ci/setup-mingw.ps1
    }

build_script:
- cmd: powershell ../ci/build.ps1

test_script:
- cmd: powershell ../ci/test.ps1
